version: '3'
services:
  app:
    build: back/
    container_name: app
    env_file: 
      - .env
    ports:
      - ${PORT_API}:5000

  mongo:
    image: mongo
    container_name: ${MONGO_HOST}
    restart: unless-stopped
    tty: true
    volumes:
      - /opt/hak_ya/mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7886:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: V63546J56UIKDAS1232
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/

  
  nginx_auth:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front:/var/www/front
      - ./data/certs:/etc/letsencrypt

  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx_auth
  #   volumes:
  #     - ./front:/var/www/front
  #     - ./data/certs:/etc/letsencrypt
  #   command: certonly --webroot --webroot-path=/var/www/front --email shaman070798@rambler.ru --agree-tos --no-eff-email -d ic-dev.ru
  #   restart: unless-stopped